Django_Demo_Blog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from account.views import refresh_captcha, IndexView
from django.conf import settings
from django.views import static

urlpatterns = [
    url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    url('admin/', admin.site.urls),
    url('blog/', include('blog.urls', namespace='blog')),
    url('captcha/', include('captcha.urls')),
    url('refresh_captcha/', refresh_captcha),
    url('yzm', IndexView.as_view()),
    url('info/', include('account.urls', namespace='info')),

]

account/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'

urlpatterns = [
    url(r'login/', views.login, name='login'),
    url(r'register/', views.register, name='register'),
]

blog/urls.py
from django.contrib import admin
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url('^index/$', views.Blog_index, name='index'),
    url('^article/(?P<article_id>[0-9]+)$', views.article_page, name='article_page'),
    url('^edit/(?P<article_id>[0-9]+)$', views.edit_page, name='edit_page'),
    url('^edit/action$', views.edit_action, name='edit_action'),
    url('^index/(?P<article_id>[0-9]+)$', views.del_page, name='del_page'),
]

account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
from django.db import models


# Create your models here.
class UserToken(models.Model):
    username = models.OneToOneField(to='Info', on_delete=models.DO_NOTHING)
    token = models.CharField('token', max_length=60)

    class Meta:
        db_table = 'user_token'
        verbose_name = verbose_name_plural = '用户token表'


TYPE = (
    ('0', '管理员'),
    ('1', '普通用户')
)


class Info(models.Model):
    type = models.CharField('类型', choices=TYPE, null=True, blank=True, default='1', max_length=1)
    username = models.CharField('用户名', max_length=100, unique=True, null=True, blank=True)
    password = models.CharField('密码', max_length=100, null=True, blank=True)
    telphone = models.CharField('电话', max_length=20, null=True, blank=True)
    create_date = models.DateTimeField('注册日期', auto_now=True, null=True, blank=True)
    update_date = models.DateTimeField('更改日期', auto_now_add=True, null=True, blank=True)

    class Meta:
        verbose_name = verbose_name_plural = '账号'

    def __str__(self):
        return self.username

blog/models.py
from django.db import models


class Article(models.Model):
    author = models.CharField("发布人", max_length=50, null=True, blank=True)
    title = models.CharField('标题', max_length=32)
    content = models.TextField('内容', null=True)
    pub_time = models.DateTimeField('发布日期', auto_now_add=True, null=True)

    class Meta:
        verbose_name = verbose_name_plural = '博客'

    def __str__(self):
        return self.title

account/views.py
from django.contrib.auth import authenticate, login as django_login
from django.shortcuts import render, redirect

# Create your views here.
from django.contrib.auth.hashers import make_password, check_password
from django.http import JsonResponse
from django.urls import reverse

from .models import UserToken, Info
from django.views.generic import View
from captcha.models import CaptchaStore
from captcha.helpers import captcha_image_url
from django.http import HttpResponse
import json
import time


def login(request):
    if request.method == 'GET':
        return render(request, 'login/login.html')
    usr = request.POST.get('username')
    pas = request.POST.get('password')
    make_password(pas)
    obj = Info.objects.filter(username=usr).first()
    if not obj:
        return render(request, 'error.html', {
            'msg': '用户不存在'
        })
    check_pas = Info.objects.filter(username=usr).values('password')[0]['password']
    cp = check_password(pas, check_pas)
    if not check_pas:
        return render(request, 'error.html', {
            'msg': '账号密码不匹配'
        })
    token = str(time.time()) + usr
    UserToken.objects.update_or_create(username=obj, defaults={'token': token})
    capt = request.POST.get("yzm")  # 用户提交的验证码
    key = request.POST.get("hash")  # 验证码答案
    if not jarge_captcha(capt, key):
        return render(request, 'login/login.html', {
            'code': 0,
            'msg': '验证码不正确'
        })
    return redirect(reverse('blog:index'))


def register(request):
    if request.method == 'GET':
        return render(request, 'login/register.html')
    user = request.POST.get('username')
    print(user)
    pwd = request.POST.get('password')
    passpwd = make_password(pwd)
    tel = request.POST.get('telphone')
    capt = request.POST.get("yzm")  # 用户提交的验证码
    key = request.POST.get("hash")  # 验证码答案
    if not jarge_captcha(capt, key):
        return render(request, 'login/register.html', {
            'code': 0,
            'msg': '验证码不正确'
        })
    obj = Info.objects.filter(username=user).first()
    if not obj:
        user = Info.objects.create(username=user, password=passpwd, telphone=tel)
        if not user:
            return render(request, 'error.html', {'msg': '创建用户失败'})
        return render(request, 'login/login.html', {'code': 1, 'msg': '注册成功'})
    else:
        return render(request, 'login/login.html', {'code': 2, 'msg': '用户已存在,注册失败'})


# 创建验证码
def captcha():
    ret = {}
    hashkey = CaptchaStore.generate_key()  # 验证码答案
    ret['hashkey'] = hashkey
    image_url = captcha_image_url(hashkey)  # 验证码地址
    ret['image_url'] = image_url
    # captcha = {'hashkey': hashkey, 'image_url': image_url}
    return JsonResponse(ret)


# 刷新验证码
def refresh_captcha(request):
    return HttpResponse(json.dumps(captcha()), content_type='application/json')


# 验证验证码
def jarge_captcha(captchaStr, captchaHashkey):
    if captchaStr and captchaHashkey:
        try:
            # 获取根据hashkey获取数据库中的response值
            get_captcha = CaptchaStore.objects.get(hashkey=captchaHashkey)
            if get_captcha.response == captchaStr.lower():  # 如果验证码匹配
                return True
        except:
            return False
    else:
        return False


class IndexView(View):
    def get(self, request):
        ret = {}
        hashkey = CaptchaStore.generate_key()  # 验证码答案
        ret['hashkey'] = hashkey
        image_url = captcha_image_url(hashkey)  # 验证码地址
        ret['image_url'] = image_url
        return JsonResponse(ret)

blog/views.py
from django.shortcuts import render
from .models import Article
from django.contrib.auth.decorators import login_required


# 主页
def Blog_index(request):
    articles = Article.objects.all()
    return render(request, "blog/index.html", {'articles': articles})


# Blog Content
def article_page(request, article_id):
    article = Article.objects.get(pk=article_id)
    all_article = Article.objects.all()
    previous = None
    next = None
    for index, article_1 in enumerate(all_article):
        if index == 0:
            previous_index = 0
            next_index = index
        elif index == len(all_article) - 1:
            previous_index = index - 1
            next_index = index
        else:
            previous_index = index - 1
            next_index = index + 1
        if str(article_1.id) == str(article_id):
            previous = all_article[previous_index]
            next = all_article[next_index]

    return render(request, "blog/blog_page.html", {'article': article,
                                                   'previous': previous,
                                                   'next': next})


# Edit Blog
def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, "blog/edit_page.html")
    else:
        article = Article.objects.get(pk=article_id)
        return render(request, "blog/edit_page.html", {'article': article})


# 撰写博客
def edit_action(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    article_id = request.POST.get('article_id')
    if article_id == '0':
        Article.objects.create(title=title, content=content)
        articles = Article.objects.all()
        return render(request, "blog/index.html", {'articles': articles})
    else:
        article = Article.objects.get(pk=article_id)
        article.title = title
        article.content = content
        article.save()
        return render(request, "blog/blog_page.html", {'article': article})


# 删除博客
def del_page(request, article_id):
    delete = Article.objects.get(pk=article_id).delete()
    if not delete:
        return render(request, 'error.html', {'msg': '删除失败'})
    return render(request, "blog/Del_page.html")

templates/base/base.html
<!DOCTYPE html>
<html lang="zh">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0,viewport-fit=cover">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="{% static 'css/weui.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/ali.css' %}">
    <script src="{% static 'js/zepto.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
{% block content %}
{% endblock %}
<div class="weui-footer" style="padding-top: 5%">
    <p class="weui-footer__links">
        <a href="javascript:void(0)" class="weui-footer__link" id="forget">忘记密码</a>
    </p>
    <p class="weui-footer__text">Copyright © 2020 By WangZhengwu | <a
            href="http://www.miitbeian.gov.cn/">湘ICP备19000714号</a></p>
</div>
</body>
</html>
<script>
    $("#forget").on('click', function () {
        alert("忘记密码请联系老王")
    });
</script>

templates/blog/Del_page.html
{% extends 'base/base.html' %}
{% block title %}删除{% endblock %}
{% block content %}
    {% load static %}
    <div class="weui_cells_title page_title" style="padding-top: 25%">
        <img src="{% static 'images/logo.jpeg' %}" style="width: 40%;height:20%;text-align: center">
    </div>
    <center>
        <h1 style="color: aqua">删除成功</h1>
        <br>
        <a href="{% url 'blog:index' %}" class="weui-btn weui-btn_primary">返回首页</a>
    </center>
{% endblock %}

templates/blog/blog_page.html
{% extends 'base/base.html' %}
{% block title %}博客详情{% endblock %}
{% block content %}
    {% load static %}
    <div class="weui_cells_title page_title">
        <img src="{% static 'images/logo.jpeg' %}" style="width: 40%;height:20%;text-align: center">
    </div>
    <div class="weui-form__control-area">
        <div class="weui-cells__group weui-cells__group_form">
            <div class="weui-cells__title" style="text-align: center">标题：{{ article.title }}</div>
            <div class="weui-cells weui-cells_form">
                <div class="weui-cell ">
                    <div class="weui-cell__bd">
                        <textarea class="weui-textarea" placeholder="博客内容" rows="3"
                                  id="content">{{ article.content }}</textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div style="padding: 0 10% 0 30%">
        <a href="{% url 'blog:edit_page' article.id %}" class="weui-btn weui-btn_mini weui-btn_primary" style="float: left;margin-right: 15%">编辑</a>
        <form action="{% url 'blog:del_page' article.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="删除" class="weui-btn weui-btn_mini weui-btn_primary">
        </form>
    </div>
    <div style="margin-top: 10%">
        <a href="{% url 'blog:article_page' previous.id %}"
           class="weui-btn weui-btn_primary">上一篇:{{ previous.title }}</a>
        <a href="{% url 'blog:article_page' next.id %}" class="weui-btn weui-btn_primary">下一篇:{{ next.title }}</a>
        </nav>
    </div>
{% endblock %}

templates/blog/edit_page.html
{% extends 'base/base.html' %}
{% block title %}老王博客{% endblock %}
{% block content %}
    <script>
        function judge() {
            var text = document.getElementById("t").value;
            var text_1 = document.getElementById("t1").value;
            if (text === "" || text_1 === "")
                alert("请输入内容");
            else {
                document.getElementById("form").submit();
            }
        }
    </script>
    <div class="weui_cells_title" style="text-align: center;color: #8b8b8b;padding-top: 15px;font-size: 20px">博客</div>
    <form action="{% url 'blog:edit_action' %}" method="post" id="form">
        {% csrf_token %}
        {% if article %}
            <input type="hidden" name="article_id" value="{{ article.id | default:'0' }}">
            <div class="weui-cell">
                <div class="weui_cell_hd"><label class="weui-label" style="width: 120px">博客标题</label></div>
                <div class="weui_cell_bd weui_cell_primary">
                    <input class="weui-input" type="text" placeholder="标题" name="title" id="t"
                           value="{{ article.title }}">
                </div>
            </div>
            <div class="weui-cell"></div>
            <div class="weui-cells__title" style="color: #0D0D0D;font-size: 16px">博客内容</div>
            <div class="weui-cells weui-cells_form">
                <div class="weui-cell">
                    <div class="weui-cell__bd">
                        <textarea class="weui-textarea" placeholder="博客内容" rows="3" name="content"
                                  id="t1">{{ article.content }}</textarea>
                    </div>
                </div>
            </div>
        {% else %}
            <input type="hidden" name="article_id" value="0">
            <div class="weui-cell">
                <div class="weui_cell_hd"><label class="weui-label" style="width: 120px">博客标题</label></div>
                <div class="weui_cell_bd weui_cell_primary">
                    <input class="weui-input" type="text" placeholder="标题" name="title" id="t">
                </div>
            </div>
            <div class="weui-cell"></div>
            <div class="weui-cells__title" style="color: #0D0D0D;font-size: 16px">博客内容</div>
            <div class="weui-cells weui-cells_form">
                <div class="weui-cell">
                    <div class="weui-cell__bd">
                        <textarea class="weui-textarea" placeholder="博客内容" rows="3" name="content" id="t1"></textarea>
                    </div>
                </div>
            </div>

        {% endif %}
        <input type="button" value="提交" onclick="judge()" class="weui-btn weui-btn_primary" style="margin-top: 10%">
        <a class="weui-btn weui-btn_primary" href="javascript:window.history.go(-1)">返回</a>
    </form>
{% endblock %}

templates/blog/index.html
{% extends 'base/base.html' %}
{% block title %}博客首页{% endblock %}
{% block content %}
    {% load static %}
    <div class="weui_cells_title page_title">
        <img src="{% static 'images/logo.jpeg' %}" style="width: 40%;height:20%;text-align: center">
    </div>
    <center>
        <h1 style="padding-top: 5%"><a href="{% url 'blog:edit_page' 0 %}" style="color: blue">新建博客</a></h1>
        {% for article in articles %}
            <div style="color: aqua;border: 1px solid #00cccc;margin-top: 5%">
                <a href="{% url 'blog:article_page' article.id %}">
                    第{{ article.id }}条:{{ article.title }}
                    <span style="margin-left: 10%;color: #0f0f0f">发布日期{{ article.pub_time }}</span>
{#                    <span>发布人{{ article.author }}</span>#}
                </a>
            </div>
            <br>
        {% endfor %}
        <a class="weui-btn weui-btn_primary" href="{% url 'info:login' %}">返回</a>
    </center>
{% endblock %}

templates/error.html
{% extends 'base/base.html' %}

{% block title %}错误{% endblock %}
{% block content %}
    <center>
        <h1 class="weui-cells__title">出现了错误 :(</h1>
        <p class="weui-cells__title" style="color: red">{{ msg }}</p>
        <a href="javascript:history.back(-1)" class="weui-btn weui-btn_primary"
           style="margin-top: 20px">返回</a>
    </center>
{% endblock %}

templates/login/login.html
{% extends 'base/base.html' %}
{% block title %}登录{% endblock %}
{% block content %}
    {% if  code == 0 %}
        <script>
            alert('{{ msg }}');
            javascript:void (0);
        </script>
    {% elif code == 1 %}
        <script>
            alert('{{ msg }}');
            javascript:void (0);
        </script>
    {% elif code == 2 %}
        <script>
            alert('{{ msg }}');
            javascript:void (0);
        </script>
    {% endif %}
    {% load static %}
    <div class="weui_cells_title page_title" style="padding-top: 10%">
        <img src="{% static 'images/logo.jpeg' %}" style="width: 40%;height:20%;text-align: center">
    </div>
    <div class="weui-form" style="padding-top: 0">
        <form action="{% url 'info:login' %}" id="form" method="post">{% csrf_token %}
            <div class="weui-form__control-area">
                <div class="weui-cells__group weui-cells__group_form" style="padding: 0 0 0 0">
                    <div class="weui-cells__title">登录信息</div>
                    <div class="weui-cells weui-cells_form">
                        <div class="weui-cell">
                            <div class="weui-cell__hd"><label class="weui-label">账号</label></div>
                            <div class="weui-cell__bd">
                                <input id="js_input" class="weui-input"
                                       placeholder="请填写账号" name="username">
                            </div>
                        </div>
                        <div class="weui-cell">
                            <div class="weui-cell__hd"><label class="weui-label">密码</label></div>
                            <div class="weui-cell__bd">
                                <input id="js_input1" type="password" class="weui-input" placeholder="请填写密码"
                                       name="password">
                            </div>
                        </div>
                        <div class="weui-cell">
                            <div class="weui-cell__hd"><label class="weui-label">验证码</label></div>
                            <input type="text" class="weui-input" placeholder="请填写验证码" name="yzm">
                            <div style="">
                                <input type="hidden" name="hash" id="hash">
                            </div>

                            <div class="divIdentifyingCode">
                                <img id="imgIdentifyingCode" style="height:40px; width: 100px; cursor: pointer;"
                                     alt="点击更换" title="点击更换"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    </div>
    </div>
    <div class="weui-form__opr-area">
        <a class="weui-btn weui-btn_primary" id="showTooltips">登录</a>
        <a class="weui-btn weui-btn_primary" href="{% url 'info:register' %}">注册</a>
    </div>
    <div class="weui-form__tips-area">
    </div>
    </div>
    <script>
        $.ajax({
            url: 'www.outputbug.com/yzm',
            success: function (data) {
                var identifyCodeSrc = data.image_url;
                form.hash.value = data.hashkey;
                let objs = document.getElementById("imgIdentifyingCode");
                objs.src = 'www.outputbug.com' + identifyCodeSrc;
            },
        });
        $("#forget").on('click', function () {
            alert("忘记密码请联系老王")
        });
        $("#showTooltips").on('click', function () {
            if (form.username.value === '') {
                alert("请填写账号")
            } else if (form.password.value === '') {
                alert("请填写密码")
            } else if (form.yzm.value === '') {
                alert("请填写验证码")
            } else {
                document.getElementById('form').submit()
            }
        });
        //更新验证码
        $("#imgIdentifyingCode").on('click', function () {
            $.ajax({
                url: 'www.outputbug.com/yzm',
                success: function (data) {
                    var identifyCodeSrc = data.image_url;
                    form.hash.value = data.hashkey;
                    let objs = document.getElementById("imgIdentifyingCode");
                    objs.src = 'www.outputbug.com' + identifyCodeSrc;
                },
            })
        });
    </script>
    <style>
        .divIdentifyingCode {
            position: absolute;
            right: 0;
            z-index: 5;
            width: 102px; /*设置图片显示的宽*/
            height: 40px; /*图片显示的高*/
            background: #e2e2e2;
            margin: 0;
        }
    </style>

{% endblock %}

templates/login/register.html
{% extends 'base/base.html' %}
{% block title %}注册{% endblock %}
{% block content %}
    {% if  code == 0 %}
        <script>
            window.history.go(-1);
            alert('{{ msg }}');
        </script>
    {% elif code == 1 %}
        <script>
            window.history.go(-1);
            alert('{{ msg }}');
        </script>
    {% endif %}
    {% load static %}
    <div class="weui_cells_title page_title" style="padding-top: 10%">
        <img src="{% static 'images/logo.jpeg' %}" style="width: 40%;height:20%;text-align: center">
    </div>
    <div class="weui-form" style="padding-top: 0">
        <form action="{% url 'info:register' %}" id="form" method="post">{% csrf_token %}
            <div class="weui-form__control-area">
                <div class="weui-cells__group weui-cells__group_form">
                    <div class="weui-cells__title">注册信息</div>
                    <div class="weui-cells weui-cells_form">
                        <div class="weui-cell">
                            <div class="weui-cell__hd"><label class="weui-label">用户名</label></div>
                            <div class="weui-cell__bd">
                                <input class="weui-input"
                                       placeholder="请填写用户名" name="username" value="">
                            </div>
                        </div>
                        <div class="weui-cell">
                            <div class="weui-cell__hd"><label class="weui-label">密码</label></div>
                            <div class="weui-cell__bd">
                                <input type="password" class="weui-input" placeholder="请填写密码" name="password">
                            </div>
                        </div>
                        <div class="weui-cell">
                            <div class="weui-cell__hd"><label class="weui-label">确认密码</label></div>
                            <div class="weui-cell__bd">
                                <input type="password" class="weui-input" placeholder="请填写密码" name="querenpwd">
                            </div>
                        </div>
                        <div class="weui-cell">
                            <div class="weui-cell__hd"><label class="weui-label">手机号码</label></div>
                            <div class="weui-cell__bd">
                                <input type="password" class="weui-input" placeholder="请填写手机号" name="telphone">
                            </div>
                        </div>
                        <div class="weui-cell">
                            <div class="weui-cell__hd"><label class="weui-label">验证码</label></div>
                            <input type="text" class="weui-input" placeholder="请填写验证码" name="yzm" value="">
                            <div style="">
                                <input type="hidden" name="hash" id="hash">
                            </div>

                            <div class="divIdentifyingCode">
                                <img id="imgIdentifyingCode" style="height:40px; width: 100px; cursor: pointer;"
                                     alt="点击更换" title="点击更换"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="weui-form__opr-area" style="margin-bottom: 50px">
        <a class="weui-btn weui-btn_primary" id="showTooltips">提交</a>
        <a class="weui-btn weui-btn_primary" href="javascript:window.history.go(-1)">返回</a>
    </div>
    </div>
    <script>
        $.ajax({
            url: 'http:www.outputbug.com/yzm',
            success: function (data) {
                var identifyCodeSrc = data.image_url;
                form.hash.value = data.hashkey;
                let objs = document.getElementById("imgIdentifyingCode");
                objs.src = 'http:www.outputbug.com' + identifyCodeSrc;
            },
        });
        var phone = /^1(3|4|5|7|8)\d{9}$/;
        var pwd = /^(?:\d+|[a-zA-Z]+|[!@#$%^&*]+){6,18}$/;
        $("#showTooltips").on('click', function () {
            if (form.username.value === '') {
                alert("请填写用户名")
            } else if (!pwd.test(form.password.value)) {
                alert("密码不正确，密码由6-18位数字、英文或特殊字符组成")
            } else if (form.querenpwd.value !== form.password.value) {
                alert("两次密码输入不一致");
                form.password.value = '';
                form.querenpwd.value = '';
            } else if (!phone.test(form.telphone.value)) {
                alert("请输入正确的手机号")
            } else if (form.yzm.value === '') {
                alert('请填写验证码')
            } else {
                document.getElementById('form').submit()
            }
        });
        //更新验证码
        $("#imgIdentifyingCode").on('click', function () {
            $.ajax({
                url: 'http:www.outputbug.com/yzm',
                success: function (data) {
                    var identifyCodeSrc = data.image_url;
                    form.hash.value = data.hashkey;
                    let objs = document.getElementById("imgIdentifyingCode");
                    objs.src = 'http:www.outputbug.com' + identifyCodeSrc;
                },
            })
        });
    </script>
    <style>
        .divIdentifyingCode {
            position: absolute;
            right: 0;
            z-index: 5;
            width: 102px; /*设置图片显示的宽*/
            height: 40px; /*图片显示的高*/
            background: #e2e2e2;
            margin: 0;
        }
    </style>
{% endblock %}